-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "tags" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "price" SET DEFAULT 0,
ALTER COLUMN "sizes" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "reviewsTotal" SET DEFAULT 0;
