version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always # necessary since it's failing to start sometimes
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: d_gala_db
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data

  s3:
    image: minio/minio:latest
    restart: always # necessary since it's failing to start sometimes
    command: server --address ":9001" --console-address ":9000" /data
    expose:
      - "9000"
      - "${MINIO_PORT}"
    ports:
      - "9000:9000"
      - "${MINIO_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./storage/minio:/data

  elasticsearch:
    image: elasticsearch:7.17.8
    restart: always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
    volumes:
      - ./storage/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200