version: '4.8.2'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: database_gala
    volumes:
      - ./postgres_db:/var/lib/postgresql/data