version: '4.8.2'

services:
  d_gala_app:
    depends_on:
      - db
      - s3
    build:
      context: .
      dockerfile: Dockerfile
    image: d_gala-docker
    container_name: d_gala_app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: postgres
    restart: always # necessary since it's failing to start sometimes
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_db:/var/lib/postgresql/data

  s3:
    image: minio/minio:latest
    restart: always # necessary since it's failing to start sometimes
    command: server --address ":9001" --console-address ":9000" /data
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./storage/minio:/data