export const minioStorage = {
  MINIO_ROOT_USER: 'MINIO_ROOT_USER',
  MINIO_ROOT_PASSWORD: 'MINIO_ROOT_PASSWORD',
  MINIO_ENDPOINT: 'MINIO_ENDPOINT',
  MINIO_PORT: 'MINIO_PORT',
  MINIO_BUCKET: 'MINIO_BUCKET',
};
