export enum SearchEnvEnum {
  NODE = 'ELASTIC_SEARCH_NODE',

  NAME = 'ELASTIC_SEARCH_NAME',

  USERNAME = 'ELASTIC_SEARCH_USERNAME',

  PASSWORD = 'ELASTIC_SEARCH_PASSWORD',

  NODE_SEARCH_LIST_PAGE_SIZE_DEFAULT = 10,

  NODE_SEARCH_LIST_PAGE_DEFAULT = 1,
}
